Add convergence limit, Add intro outro

diff --git a/batchScript b/batchScript
--- a/batchScript
+++ b/batchScript
@@ -25,11 +25,21 @@ echo "========== MPI LAUNCHER for iso3d to use with sbatch =========="
 #@param -f = -d debug option 
 numberProcess=-1
 user=-1
-method=-1
+method=""
 iter=-1
 ants=-1
 delta=-1
 rho=-1
+
+
+show_help() {
+python3 ACO-mpi-scatter.py -h
+}
+
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+    show_help
+    exit 0
+fi
 
 while getopts 'n:u:m:i:a:d:r' flag; do
     case "${flag}" in
@@ -42,8 +52,6 @@ while getopts 'n:u:m:i:a:d:r' flag; do
         r) rho="${OPTARG}" ;;
     esac
 done
-echo $rho
-echo $delta
 if ! [[ "$numberProcess" =~ ^[1-8]+$ ]]; then
     echo "Error: Argument numberProcess is not between 1 and 8"
     exit 128
@@ -52,8 +60,8 @@ if ! [[ "$user" =~ ^[1-9]+$ ]]; then
     echo "Error: Argument user is not a number from 1-9"
     exit 128
 fi
-if ! [[ "$method" =~ ^[1-9]+$ ]]; then
-    echo "Error: Argument method is not a number from 1-9"
+if [[ "$method" != "linear" && "$method" != "quadratic" && "$method" != "relu"]]; then
+    echo "Error: Argument method must be one of GET, POST, PUT, DELETE."
     exit 128
 fi
 if ! [[ "$iter" =~ ^[0-9]+$ ]]; then
@@ -64,14 +72,16 @@ if ! [[ "$ants" =~ ^[0-9]+$ ]]; then
     echo "Error: Argument ants is not a number"
     exit 128
 fi
+if ! [[ "$delta" =~ ^[0-9]+[.][0-9]+$ ]]; then
+    echo "Error: Argument delta is not a float"
+    exit 128
+fi
+if ! [[ "$rho" =~ ^[0-9]+[.][0-9]+$ ]]; then
+    echo "Error: Argument rho is not a float"
+    exit 128
+fi
 
 echo "===================== MPIRUN ======================="
-# --user [your user number]
-# --distribution n : 1 for Linear, 2 for Quadratic, 3 for ReLU
-/usr/bin/mpirun -np $numberProcess -map-by ppr:1:node:PE=16 -rank-by core python3 ACO-mpi-scatter.py --user $user --method $method --iter $iter --nbants $ants --delta 0.1 --rho 0.1
-# ex to test 4 processes on one node (no communications)
-#/usr/bin/mpirun -np 4 -map-by ppr:1:core:PE=1 -rank-by core python3 myappli.py args_of_my_appli
-
-
+/usr/bin/mpirun -np $numberProcess -map-by ppr:1:node:PE=16 -rank-by core python3 ACO-mpi-scatter.py --user $user --method $method --iter $iter --nbants $ants --delta $delta --rho $rho
 echo "===================== END ======================="
 
